name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gnuplot
      run: sudo apt-get install -y gnuplot
    - uses: actions/checkout@v3
    - name: Benchmarking
      run: cargo bench
    - name: Archive benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: criterion-report
        path: target/criterion/