name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@nextest
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo nextest run
